
name: caixa-hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - langchain=0.3.3
  - matplotlib=3.9.2
  - pandas=2.2.3
  - requests=2.32.3
  - seaborn=0.13.2
  - fpdf2=2.8.1
  - pytest=8.3.3
  - xgboost
  - scikit-learn
  - tqdm
  - ipykernel
  - lightning
  - pip:
    - ollama==0.3.3
    - langchain-ollama==0.2.0
    - pytorch-forecasting
